<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  
  <!--async await-->
  <script>
    // 只要返回的不是一个promist对象，那么这个返回的就是一个promise对象
    async function fn() {
      //正常返回，返回的就是一个成功的promise
      return 'fzw';
      //如果抛出异常，返回的就是一个失败的promise
    }
    const result = fn();
    console.log(result);
  </script>

  <!--await-->
  <script>
    //创建一个promist
    const p = new Promise((resolve, reject)=>{
      resolve("成功的值");
    })
    //await必须啊在async函数中
    // await右侧一般是返回的是一个promise对象
    // await返回的是promise成功的值
    // await如果失败了，就会抛出异常
    async function fu() {
      try {
        let result = await p
        console.log(result)
      } catch (e) {
        console.log(e)
      }
    }    
  </script>
</body>
</html>